/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boom;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author larryvolz
 */
public class MainMenu extends javax.swing.JFrame {
    
    public boolean GameIsLive = false; 

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        
        
        //jSpinner1.getComponent(0).setPreferredSize(new Dimension(100,100));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        timeDropDown = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        beginButton.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        beginButton.setText("BEGIN GAME");
        beginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel1.setText("Game Length:");

        timeDropDown.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        timeDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "60", "45", "30" }));
        timeDropDown.setMinimumSize(new java.awt.Dimension(167, 45));
        timeDropDown.setSize(new java.awt.Dimension(96, 50));
        timeDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeDropDownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(timeDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeDropDown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(beginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginButtonActionPerformed
                
                //int timeInMinutes = (int)(jSpinner1.getValue());
                //int timeInSeconds = ((int)(jSpinner1.getValue())*60);
                
                //Get info from dropdown box
                String timeSelected = timeDropDown.getSelectedItem().toString();
                
                int timeInMinutes;
                int timeInSeconds;
                
                switch (timeSelected) {
                    case "60":
                        timeInMinutes = 60;
                        break;
                    case "45":
                        timeInMinutes = 45;
                        break;
                    case "30":
                        timeInMinutes = 30;
                        break;
                    default:
                        timeInMinutes = 60;
                        break;
                }
                
                timeInSeconds = timeInMinutes*60;
               
                               
                counter.counter2.setCounter(timeInSeconds);        
        
                
                setGameIsLive(true);
                //counter count = new counter();
                
                System.out.println("counter is: " + counter.counter2.getCounter());
                
                
                
                
                this.setVisible(false);
                
                //Play Countdown Audio
                /*
                String fileName;
                switch (timeInMinutes){
                    case 60:
                         fileName = "AudioFiles/60before.wav";
                        break;
                    case 45:
                         fileName = "AudioFiles/45before.wav";
                        break;
                     case 30:
                         fileName = "AudioFiles/30before.wav";
                        break;  
                     default:
                         fileName = "AudioFiles/60before.wav";
                         break;
                   
                }
                */
                
                
                String fileName = "AudioFiles/"+timeSelected+"before.wav";
               
                //String fileName = "AudioFiles/"+"timeInMinutes"+"before.wav";
                
                PlayAudio.playAudio(fileName);
                
                new Countdown().setVisible(true);
                


    }//GEN-LAST:event_beginButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened

    private void timeDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeDropDownActionPerformed
        // TODO add your handling code here:
        //String timeSelected = timeDropDown.getSelectedItem().toString();
        
        
        //System.out.println("item from dropdown box = "+timeSelected);
    }//GEN-LAST:event_timeDropDownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> timeDropDown;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the GameIsLive
     */
    public boolean isGameIsLive() {
        return GameIsLive;
    }

    /**
     * @param GameIsLive the GameIsLive to set
     */
    public void setGameIsLive(boolean GameIsLive) {
        this.GameIsLive = GameIsLive;
    }
}
